name: detekt

on:
  push:
    branches: [ master ]
jobs:
   detekt:
     runs-on: self-hosted

     steps:
       - name: "checkout"
         uses: actions/checkout@v4

       - name: "detekt"
         uses: natiginfo/action-detekt-all@1.23.7
